package edu.nd.paradigms.hw3.algorithm

import edu.nd.paradigms.hw3.Representation
import edu.nd.paradigms.hw3.States
import edu.nd.paradigms.hw3.UnsolvableApportionmentException

/**
 * Represents the apportionment method proposed by Thomas Jefferson, adopted in the 1792 and used until 1842, when
 * the Webster method was adopted. Also called <a href="https://en.wikipedia.org/wiki/D%27Hondt_method">the
 * D'Hondt method</a>
 */
class JeffersonMethod: ApportionmentMethod {
    /**
     * Gets the apportionment generated by the Jefferson algorithm. Uses a binary search to find the
     * appropriate divisor.
     * @param states the group of {@link States} to allocate representatives to.
     * @param seats the number of seats in Congress to allocate
     * @return {@link Representation}
     * @throws IllegalArgumentException if it is not possible to apportion the given number of representatives
     * mathematically (often due to ties between states whose populations have common factors)
     */
    override fun getRepresentation(
        states: States,
        representatives: Int
    ): Representation {
        require(states.isNotEmpty && states.totalPopulation > 0) { "No states provided! Cannot generate Representation map!" }
        require(representatives > 0) { "Number of representatives must be greater than zero!" }

        var highDivisor = states.getAverageRepresentation(representatives)
        var lowDivisor = 0.0

        repeat(100) {
            val midDivisor = (highDivisor + lowDivisor) / 2.0
            val roundedDownQuotas = states.getRoundedDownQuotas(midDivisor)
            val representation = Representation(roundedDownQuotas)

            if (representation.allocatedSeats > representatives) {
                lowDivisor = midDivisor
            } else if (representation.allocatedSeats < representatives) {
                highDivisor = midDivisor
            } else {
                return representation
            }
        }
        throw UnsolvableApportionmentException(
            "Unsolvable Jefferson Apportionment with the given parameters; it is likely that is is an unresolvable tie"
        )
    }
}